# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'The-Shop-App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for The-Shop-App
  def shopapp_pods
    pod 'Firebase', '>= 2.5.1'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'CariocaMenu'
  end

  shopapp_pods

  target 'The-Shop-AppTests' do
    inherit! :search_paths
    # Pods for testing
    shopapp_pods
  end

end
